### ISSUE TITLE
Prohibit units correctly

### ISSUE THREAD

**Issue by ezhlobo** [datarockets/stylelint-config#10]
Here is what we need for correct units:

```
  declaration-property-unit-blacklist:
    /^(border(?!-radius))/:
      - rem
      - em
      - "%"

    /^[^-]{2}?.+/:
      - px

  declaration-property-unit-whitelist:
    letter-spacing:
      - em

  unit-whitelist:
    - px
    - vh
    - vw
    - vmin
    - vmax
    - rem
    - em
    - "%"
    - s
    - ms
    - deg
```

Probably need to write tests and think up better way to handle it
